### PR TITLE
Autoprotocol branch: HSA competition assay example added.

### PR DESCRIPTION
**Pull request by MehtapIsik**
I have added HSA competition assay data of 2015/20/12 experiment to `assaytools/data/hsa_competition_assay/`. It has all necessary files (Infinite result, D300 simulation data, DMSO stock solution table ) and a short description.

### CODE REVIEW

**Comment by MehtapIsik** [comment]
I think as a starting example we should analyze row A and C.
Row A:  HSA + Dansylamide titration
Row C : HSA + Dansylamide titration + constant concentration of phenylbutazone (10 uM)

**Comment by jchodera** [comment]
@MehtapIsik: This PR included a huge number of upstream changes, so I just merged them in separately and this seems to have caused a conflict with your PR. Can you isolate just those files you need to add and then open a separate PR? Or add them directly to the upstream `master` in a separate PR?

Sorry about this!

**Comment by MehtapIsik** [comment]
I'll make a separate PR to add this data to choderalab master branch of assaytools.

**Comment by MehtapIsik** [comment]
I started another PR to choderalab/assaytools master branch: https://github.com/choderalab/assaytools/pull/63.

I am closing this PR.

**Pull request closed without merging**
